import { library } from "@fortawesome/fontawesome-svg-core";
import { fab } from "@fortawesome/free-brands-svg-icons";
import * as FA from "@fortawesome/free-solid-svg-icons";

library.add(
  fab,
  FA.faSearch,
  FA.faBars,
  FA.faPlay,
  FA.faHome,
  FA.faEye,
  FA.faUsers,
  FA.faBook,
  FA.faFireAlt,
  FA.faPhone,
  FA.faQuestionCircle,
  FA.faSearch,
  FA.faTimes,
  FA.faCogs,
  FA.faAngleDoubleDown,
  FA.faAngleDoubleUp,
  FA.faAngleUp,
  FA.faAngleDown,
  FA.faImage,
  FA.faMapMarked,
  FA.faMapMarkedAlt,
  FA.faTags,
  FA.faCalendar,
  FA.faComments,
  FA.faCircle,
  FA.faMapMarkerAlt,
  FA.faCalendarAlt,
  FA.faVideo,
  FA.faEnvelope,
  FA.faArrowCircleUp,
  FA.faArrowCircleDown,
  FA.faPencilAlt,
  FA.faEdit,
  FA.faStar,
  FA.faStarHalf,
  FA.faStarHalfAlt,
  FA.faUserFriends,
  FA.faIdCard
);
