# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-12 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
