# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-15 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_auto_20190412_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='gear',
            field=models.TextField(blank=True, null=True, verbose_name=b'Recommended Gear'),
        ),
    ]
