# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-17 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_auto_20190416_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='starting_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_starting_location', to='trips.Location'),
        ),
    ]
